### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by isuran** [gamonoid/icehrm#12] opened 2016-03-08 10:53 UTC
admin/admin is not working. there are 29 tables in database, is that OK.

**Comment by p418** [comment] 2016-06-14 13:12
Using 16.1 and same problem here.

I tried to directly execute both `scripts/icehrmdb.sql` and `scripts/icehrm_master_data.sql`  scripts and get SQL error durring tables creation.

**Comment by p418** [comment] 2016-06-16 17:55
Ok, I've succeeded in setting up tables.

If, like me, you've got same error when performing script execution: 

```
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'birthday'                                                                                                                                                           
ERROR 1067 (42000): Invalid default value for 'last_login'                                                                                                                                                         
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
ERROR 1067 (42000): Invalid default value for 'created'                                                                                                                                                            
....
```

It's caused by the use of default value `0000-00-00 00:00:00` for `TIMESTAMP` fields and following sql mode:

```sql
mysql> select @@GLOBAL.SQL_MODE;                                                                                                                                                                                   
+-------------------------------------------------------------------------------------------------------------------------------------------+                                                                      
| @@GLOBAL.SQL_MODE                                                                                                                         |                                                                      
+-------------------------------------------------------------------------------------------------------------------------------------------+                                                                      
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |                                                                      
+-------------------------------------------------------------------------------------------------------------------------------------------+                                                                      
1 row in set (0.00 sec)             
```

Remove those two options `NO_ZERO_IN_DATE,NO_ZERO_DATE` by setting 

```sql
set sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

or the globals:

```sql
set global sql_mode=...
```

**Comment by thilinah** [comment] 2016-08-05 03:32
Also please make sure MySQL strict mode is disabled.

**Comment by trekkervnc** [comment] 2016-09-20 03:49
Hi I cant log in using admin/admin or the one i supplied in the installation process,
 using xammp to create db, 
create new user and grant privilege to user,
fill in details in installation process using similar username and password from above step
test database connectivity success
then this part hang and nothing happen (install Application)
reinstall folder and content for icehrm
create new database
grant privilege to user
rerun installation
test database connectivity success
install Application success
login screen loads (but still cant log in)
reload login screen (sometimes nothing happen)
clear data folder and delete config.php file
re load installation
test database connectivity (success)
Intall Application (Hang again)
Please help....

**Comment by nsrosenqvist** [comment] 2017-06-08 04:40
I downloaded the latest release (v19.0.OS) and experienced the same issue. The tables Users and Employees don't get created and even after configuring the db script so that it includes the previous mentioned fix I can't login. I get passed the login screen but it never finishes loading the dashboard.

**Comment by starlight-tu** [comment] 2017-06-28 02:32
I have the same problem like you guys and I also use v19.0.OS like @nsrosenqvist 
And I didn't even know the two tables (Users, Employees) actually exist (newbie - LOL)

BTW, I use wamp x32 v.3.0.6 for hosting the IceHRM.

What should I do now? Because the trick above won't help me. Should I downgrade?

**Comment by thilinah** [comment] 2017-11-26 20:16
Almost all the issues here are fixed now

**Closed by thilinah** 2017-11-26 20:16 UTC

**Comment by splax-s** [comment] 2024-06-22 18:33
> Hi I cant log in using admin/admin or the one i supplied in the installation process, using xammp to create db, create new user and grant privilege to user, fill in details in installation process using similar username and password from above step test database connectivity success then this part hang and nothing happen (install Application) reinstall folder and content for icehrm create new database grant privilege to user rerun installation test database connectivity success install Application success login screen loads (but still cant log in) reload login screen (sometimes nothing happen) clear data folder and delete config.php file re load installation test database connectivity (success) Intall Application (Hang again) Please help....

me too
