### ISSUE TITLE
User session is not validated correctly

### ISSUE THREAD

**Issue by vikasro** [gamonoid/icehrm#113] opened 2018-05-07 05:51 UTC
After logging out from application it automatically giving access to admin .

**Comment by thilinah** [comment] 2018-05-07 05:53
Can you please give details about your server environment? If possible please share a short screen capture of the issue.

**Comment by vikasro** [comment] 2018-05-07 06:14
Here is demo : https://youtu.be/aQ-GeXOrYAE
cPanel Version | 62.0 (build 28)
Apache Version | 2.2.34
PHP Version | 5.4.43
MySQL Version | 5.5.44-37.3
Architecture | x86_64
Operating System | linux
Perl Version | 5.10.1
Kernel Version | 2.6.32-673.8.1.lve1.4.3.el6.x86_64

**Comment by thilinah** [comment] 2018-05-07 08:37
Also, this is not a problem with the user session. When you select "Remember me" option a token is stored in your browser as a cookie which is used to log you in next time you load the application. The problem is this cookie not getting cleared if the user logged out.

**Comment by thilinah** [comment] 2018-05-08 05:59
No worries, It's already fixed and will be released in next version.

**Closed by thilinah** 2018-05-08 05:59 UTC
